### ISSUE TITLE
图5里面的公式存在问题哈

### ISSUE THREAD

**Issue by xuyu666** [LPengYang/FreeDrag#10]
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/047f8fd8-038b-41f5-99f7-3838a609f69c)

**Comment by LPengYang** [comment]
字体出问题了 ，我们会在新版中改进framework图。感谢~
>

**Comment by xuyu666** [comment]
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/eb95fddc-24f8-43a1-9a9c-fd16b644cb59)
这里还有一处小错误哈。
没事哈哈，看到就顺带提出来了~

**Comment by xuyu666** [comment]
另外想问一下，这个真实图像编辑你有写接口么，原始代码跑出来的gradio貌似没看到。
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/47378f22-ac69-4f48-9f39-57405257e9b7)
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/3284fe96-5532-430a-904f-d990f5498a2c)

**Comment by LPengYang** [comment]
> ![image](https://user-images.githubusercontent.com/49869475/276531715-eb95fddc-24f8-43a1-9a9c-fd16b644cb59.png) 这里还有一处小错误哈。 没事哈哈，看到就顺带提出来了~

嗯嗯，范数符号有点问题，我们会一起修改。

**Comment by LPengYang** [comment]
> 另外想问一下，这个真实图像编辑你有写接口么，原始代码跑出来的gradio貌似没看到。 ![image](https://user-images.githubusercontent.com/49869475/276532924-47378f22-ac69-4f48-9f39-57405257e9b7.png) ![image](https://user-images.githubusercontent.com/49869475/276533044-3284fe96-5532-430a-904f-d990f5498a2c.png)

可以的，FreeDrag的最新版本支持对真实图片的编辑，我们没有单独写接口，只需要点击生成的图片右上角×号然后点击空白区域就可以导入自己的图片，对于导入的图片会自动执行图片反转因此会耗时更长(~120s)，反转后的编辑流程一致。在线体验链接(支持真实图片反转): https://openxlab.org.cn/apps/detail/LPengYang/FreeDrag
有用户反映目前的参考的图像反转功能不够好，我们也在尝试新的反转方法以提高质量。
FreeDrag基于Diffusion的图片反转和编辑能力也在测试中，将会在近期上线。
所有这些改进都会包含在我们的下一次更新中~

**Comment by LPengYang** [comment]
> 另外想问一下，这个真实图像编辑你有写接口么，原始代码跑出来的gradio貌似没看到。 ![image](https://user-images.githubusercontent.com/49869475/276532924-47378f22-ac69-4f48-9f39-57405257e9b7.png) ![image](https://user-images.githubusercontent.com/49869475/276533044-3284fe96-5532-430a-904f-d990f5498a2c.png)

嗯嗯，FreeDrag的当前版本支持对真实图片的编辑，我们没有单独写接口，只需要点击生成图片右上角的×号然后点击图片空白区域就可以上传自己的图片，真实图片需要先反转所以需要耗时更久(~120s in V100), 反转完成后编辑流程一致。[在线体验链接](https://openxlab.org.cn/apps/detail/LPengYang/FreeDrag)

有用户反映当前使用的图片反转函数反转质量不高，我们在积极测试新的反转函数以实现更高的反转质量。

此外，Diffusion-based FreeDrag (support Diffusion-based real image inversion AND image drag editing)目前正在测试中，将会在近期上线~

所有的改进都会包含在下次更新中。

**Comment by xuyu666** [comment]
好的哈，我刚刚用真实图像测试了，确实可以反演。
如果可以的话，可以优化下gradio的展示逻辑，更加符合人的习惯~（例如，用两个窗口展示编辑前后的图）
加油老哥，干巴碟~

**Comment by LPengYang** [comment]
> 好的哈，我刚刚用真实图像测试了，确实可以反演。 如果可以的话，可以优化下gradio的展示逻辑，更加符合人的习惯~（例如，用两个窗口展示编辑前后的图） 加油老哥，干巴碟~

基于Diffusion的FreeDrag 已经上传了，支持真实图像反转-拖拽编辑和 直接编辑生成的图片(SD-1.5)。我们会在之后几天更新实施的细节。

**Comment by LPengYang** [comment]
Hi, the updated paper is now available, which contains more implementation details on both GAN-based models and Diffusion models.

**Comment by xuyu666** [comment]
哈喽，有跟进更新后的论文，其中公式11是否有误？同时下面这行代码是否应该求和而不是求均值。实验发现求均值的编辑能力较弱，但编辑时间较短。
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/11c91081-fa0e-4198-b981-3ac03f616249)
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/8c069c25-3a1c-442f-9b87-ef3c07b9c15a)

**Comment by LPengYang** [comment]
Hi,你好，第二项确实应该是mask 的loss;  求均值和求和本质上其实是决定mask loss 的权重(可调)，这个权重可以根据每张图片和特定的编辑需求做调整， 求和其实是增大了mask loss, 保护能力增强相应地编辑速度变慢。.L1 loss 默认是求均值所以这里用的是求均值。
