### ISSUE TITLE
关于diffusion版本的问题

### ISSUE THREAD

**Issue by Donkdot** [LPengYang/FreeDrag#13]
你好！我在diffusion版本中测试动态更新策略的有效性时，将系数设置为0后，编辑后没有一点效果，请问这样是正常的吗？
![PixPin_2024-03-04_10-42-33](https://github.com/LPengYang/FreeDrag/assets/112056872/64c3cf0d-e5f2-41f2-8767-c2c3f522b201)

**Comment by LPengYang** [comment]
你好， 你指的系数具体是指？用默认参数有效果嘛？diffusion 相比于stylegan 确实是更难拖动的。

**Comment by Donkdot** [comment]
![PixPin_2024-03-04_10-58-20](https://github.com/LPengYang/FreeDrag/assets/112056872/07ad6a51-506d-4079-89b9-e49e5db459a2)
默认参数是有效果的，但是按照您在文中消融实验中提到的，将公式三中的系数设置为0之后，就完全没有效果了

**Comment by Donkdot** [comment]
您之前是否在diffusion上测试过这个模块的有效性呢？目前来看确实是十分有效的，去掉之后直接没有一点编辑效果了，但是感觉这样又不太符合逻辑

**Comment by LPengYang** [comment]
嗯嗯，这确实是可能的。一方面diffusion 相比于stylegan 本身就更难被拖动(因为特征没有被充分解耦),另一方面，xishu 置为0 相当于拒绝任何更新(即在drag 过程中强制一模一样的特征转移), 这可能并不在约束的解空间内。实际上，在stylegan的模型中也能观察到类似现象，但是程度会小很多(因为stylegan的模型的浅层特征表征结构，更容易拖动特征只改变结构而保留appearance).

**Comment by LPengYang** [comment]
嗯嗯，这确实是可能的。一方面diffusion 相比于stylegan 本身就更难被拖动(因为特征没有被充分解耦),另一方面，xishu 置为0 相当于拒绝任何更新(即在drag 过程中强制一模一样的特征转移), 这本身并不合理（拖动本身就伴随着特征的改变)。实际上，在stylegan的模型中也能观察到类似现象，但是程度会小很多(因为stylegan的模型的浅层特征表征结构，更容易拖动特征只改变结构而保留appearance).

**Comment by Donkdot** [comment]
我理解了 谢谢您这么快的回复！
