### ISSUE TITLE
wget有点慢，有其他传输方式么啊哈哈哈

### ISSUE THREAD

**Issue by xuyu666** [LPengYang/FreeDrag#3]
wget 'https://api.ngc.nvidia.com/v2/models/nvidia/research/stylegan2/versions/1/files/stylegan2-ffhq-512x512.pkl'

运行的时候有点慢，期待有其他下载方式哈哈。
![image](https://github.com/LPengYang/FreeDrag/assets/49869475/03b3d272-e096-4958-8267-8040874b119c)

![image](https://github.com/LPengYang/FreeDrag/assets/49869475/218f3c58-3fbe-47af-b572-b644566b4914)

**Comment by LPengYang** [comment]
有的时候下载速度就是很慢，如果发现特别慢，你可以尝试终止下载然后重新开始(已下载的模型会被删除然后重新开始),对于第一个模型，你可以直接用这个下载链接：https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files 注意选择对应的模型（ffhq-512×512）并将下载的模型命名为faces.pkl。

**Comment by xuyu666** [comment]
好的，谢谢你~
