### ISSUE TITLE
可以训练么

### ISSUE THREAD

**Issue by xuyu666** [LPengYang/FreeDrag#5]
您好，想请问一下如何进行代码训练，想用自己的数据集试试哈哈。
ps：如果可以，能指导下流程么~

**Comment by LPengYang** [comment]
Hi, 代码并不需要训练，目前仅支持对stylegan生成的图片进行编辑，后续会加入对真实图片的编辑功能，真实图片需要多加一步将图片反转到letent code的步骤。两者都不需要对stylegan的模型进行重新训练，本质上“drag”的过程是zero-shot的，拖拽的过程就是使用优化器寻找对应latent code的过程。

**Comment by xuyu666** [comment]
明白了，如果我用在与人脸数据分布较大的数据时，我应该自己预训练好style gan权重，然后按照drag流程走就行对么

徐玉
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Pengyang Ling< ***@***.***>Date:2023-07-24 11:59:01To:LPengYang/FreeDrag< ***@***.***>Cc:xuyu666< ***@***.***>、Author< ***@***.***>Subject:Re: [LPengYang/FreeDrag] 可以训练么 (Issue #5)
Hi, 代码并不需要训练，目前仅支持对stylegan生成的图片进行编辑，后续会加入对真实图片的编辑功能，真实图片需要多加一步将图片反转到letent code的步骤。两者都不需要对stylegan的模型进行重新训练，本质上“drag”的过程是zero-shot的，拖拽的过程就是使用优化器寻找对应latent code的过程。

**Comment by LPengYang** [comment]
> 明白了，如果我用在与人脸数据分布较大的数据时，我应该自己预训练好style gan权重，然后按照drag流程走就行对么 徐玉 ***@***.*** 签名由 网易灵犀办公 定制 Original: From:Pengyang Ling< ***@***.***>Date:2023-07-24 11:59:01To:LPengYang/FreeDrag< ***@***.***>Cc:xuyu666< ***@***.***>、Author< ***@***.***>Subject:Re: [LPengYang/FreeDrag] 可以训练么 (Issue #5) Hi, 代码并不需要训练，目前仅支持对stylegan生成的图片进行编辑，后续会加入对真实图片的编辑功能，真实图片需要多加一步将图片反转到letent code的步骤。两者都不需要对stylegan的模型进行重新训练，本质上“drag”的过程是zero-shot的，拖拽的过程就是使用优化器寻找对应latent code的过程。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

嗯嗯，如果是完全不同的数据，你需要预训练一个stylgegan。我们后续也计划和diffsuion model做结合以接触对预训练的stylegan的依赖。

**Comment by LPengYang** [comment]
> 明白了，如果我用在与人脸数据分布较大的数据时，我应该自己预训练好style gan权重，然后按照drag流程走就行对么 徐玉 ***@***.*** 签名由 网易灵犀办公 定制 Original: From:Pengyang Ling< ***@***.***>Date:2023-07-24 11:59:01To:LPengYang/FreeDrag< ***@***.***>Cc:xuyu666< ***@***.***>、Author< ***@***.***>Subject:Re: [LPengYang/FreeDrag] 可以训练么 (Issue #5) Hi, 代码并不需要训练，目前仅支持对stylegan生成的图片进行编辑，后续会加入对真实图片的编辑功能，真实图片需要多加一步将图片反转到letent code的步骤。两者都不需要对stylegan的模型进行重新训练，本质上“drag”的过程是zero-shot的，拖拽的过程就是使用优化器寻找对应latent code的过程。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

嗯嗯，如果是完全不同的数据，你需要预训练一个stylegan来拟合对应的数据分布。我们后续计划通过和diffusion model相结合来解除对stylegan的依赖。

**Comment by xuyu666** [comment]
好的，谢谢你哈哈～

徐玉
***@***.***

签名由 网易灵犀办公 定制


Original:
From:Pengyang Ling< ***@***.***>Date:2023-07-24 12:08:06To:LPengYang/FreeDrag< ***@***.***>Cc:xuyu666< ***@***.***>、Author< ***@***.***>Subject:Re: [LPengYang/FreeDrag] 可以训练么 (Issue #5)
明白了，如果我用在与人脸数据分布较大的数据时，我应该自己预训练好style gan权重，然后按照drag流程走就行对么 徐玉 @.*** 签名由 网易灵犀办公 定制 Original: From:Pengyang Ling< @.>Date:2023-07-24 11:59:01To:LPengYang/FreeDrag< @.>Cc:xuyu666< @.>、Author< @.>Subject:Re: [LPengYang/FreeDrag] 可以训练么 (Issue #5) Hi, 代码并不需要训练，目前仅支持对stylegan生成的图片进行编辑，后续会加入对真实图片的编辑功能，真实图片需要多加一步将图片反转到letent code的步骤。两者都不需要对stylegan的模型进行重新训练，本质上“drag”的过程是zero-shot的，拖拽的过程就是使用优化器寻找对应latent code的过程。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>
嗯嗯，如果是完全不同的数据，你需要预训练一个stylgegan。我们后续也计划和diffsuion model做结合以接触对预训练的stylegan的依赖。
