### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by Sylvie-X** [LPengYang/FreeDrag#6]
请问有算一些评估指标吗？DragGAN论文中有2套评估方式，您有用它们比较过吗？

**Comment by LPengYang** [comment]
Hi, DragGAN目前还没开源它们的测试代码(比如测试的图片),所以目前我们还没算评估指标，我们后续会参考 DragGAN的setting并结合dragdiffsuion完成定量评价部分。

**Comment by LPengYang** [comment]
> 请问有算一些评估指标吗？DragGAN论文中有2套评估方式，您有用它们比较过吗？
Hi, the updated paper is now available, which contains more implementation details on both GAN-based models and Diffusion models. 文章中包含对基于GAN和Diffusion 的Dragging editing的定量评估。

**Comment by Sylvie-X** [comment]
您好，请问论文中提出的FreeDragBench什么时候开源呀？

**Comment by LPengYang** [comment]
> 您好，请问论文中提出的FreeDragBench什么时候开源呀？

Hi,您好， 数据集可以在以下网址下载(https://drive.google.com/file/d/188CHb2oKVftpeVJtxqo-coz96z3KpFCm/view?usp=drive_link), 总共包含三个部分： 源图片；带rows的展示图片; 对应的随机种子和point 的坐标。 如果您在使用时遇到任何问题请随时和我们联系~

**Comment by Sylvie-X** [comment]
您好，非常感谢！




在 2024-01-02 19:29:47，"Pengyang Ling" ***@***.***> 写道：

您好，请问论文中提出的FreeDragBench什么时候开源呀？

Hi,您好， 数据集可以在以下网址下载(https://drive.google.com/file/d/188CHb2oKVftpeVJtxqo-coz96z3KpFCm/view?usp=drive_link), 总共包含三个部分： 源图片；带rows的展示图片; 对应的随机种子和point 的坐标。 如果您在使用时遇到任何问题请随时和我们联系~

**Comment by Sylvie-X** [comment]
您好：这个数据集中似乎存在一个问题，没有horses对应种子和坐标的文件horses.jsonl，与之相对地多了一个bicycles.jsonl













在 2024-01-02 19:29:47，"Pengyang Ling" ***@***.***> 写道：

您好，请问论文中提出的FreeDragBench什么时候开源呀？

Hi,您好， 数据集可以在以下网址下载(https://drive.google.com/file/d/188CHb2oKVftpeVJtxqo-coz96z3KpFCm/view?usp=drive_link), 总共包含三个部分： 源图片；带rows的展示图片; 对应的随机种子和point 的坐标。 如果您在使用时遇到任何问题请随时和我们联系~

**Comment by LPengYang** [comment]
> 您好：这个数据集中似乎存在一个问题，没有horses对应种子和坐标的文件horses.jsonl，与之相对地多了一个bicycles.jsonl 在 2024-01-02 19:29:47，"Pengyang Ling" ***@***.***> 写道： 您好，请问论文中提出的FreeDragBench什么时候开源呀？ Hi,您好， 数据集可以在以下网址下载(https://drive.google.com/file/d/188CHb2oKVftpeVJtxqo-coz96z3KpFCm/view?usp=drive_link), 总共包含三个部分： 源图片；带rows的展示图片; 对应的随机种子和point 的坐标。 如果您在使用时遇到任何问题请随时和我们联系~ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>
您好，非常感谢，我们已经做了相应的更新，数据集链接如下：
https://drive.google.com/file/d/1p2muR6aW6fqEGW8yTcHl86DCuUkwgtNY/view?usp=sharing
